// [게시판 공통] -----------------------------------------
// [진로카페] 게시판 타입 탭(조회) 타입변경(ALL, QUESTION, SHARE, FREE)
export const CHANGE_BOARD_TYPE_TAB = "CHANGE_BOARD_TYPE_TAB";
// [진로카페] 게시판 타입 필터 변경(ALL, QUESTION, SHARE, FREE)
export const CHANGE_BOARD_TYPE_FILTER = "CHANGE_BOARD_TYPE_FILTER";
// [진로카페] 게시판 타입 에디터 변경(ALL, QUESTION, SHARE, FREE)
export const CHANGE_BOARD_TYPE_EDITOR = "CHANGE_BOARD_TYPE_EDITOR";
// [진로카페] 게시판 타입데이터 조회
export const GET_BOARD_TYPE_ASYNC = "GET_BOARD_TYPE_ASYNC";
// [진로카페] 게시판 카테고리 필터 변경(EMPLOYMENT, FOUNDED)
export const CHANGE_BOARD_CATEGORY_FILTER = "CHANGE_BOARD_CATEGORY_FILTER";
// [진로카페] 게시판 카테고리 에디터 변경(EMPLOYMENT, FOUNDED)
export const CHANGE_BOARD_CATEGORY_EDITOR = "CHANGE_BOARD_CATEGORY_EDITOR";
// [진로카페] 게시판 카테고리데이터 조회
export const GET_BOARD_CATEGORY_ASYNC = "GET_BOARD_CATEGORY_ASYNC";

// [게시판 CRUD] -----------------------------------------
export const POST_BOARD_ASYNC = "POST_BOARD_ASYNC";
export const PUT_BOARD_ASYNC = "PUT_BOARD_ASYNC";
export const REMOVE_BOARD_ASYNC = "REMOVE_BOARD_ASYNC";

// [게시판 검색(자동완성) 리스트] -----------------------------------------
export const GET_SEARCH_BOARD_AUTO_COMLETE_LIST = "GET_SEARCH_BOARD_AUTO_COMLETE_LIST";
export const INIT_SEARCH_BOARD_AUTO_COMLETE_LIST = "INIT_SEARCH_BOARD_AUTO_COMLETE_LIST";

// [게시판 리스트] -----------------------------------------
export const INIT_BOARD_LIST = "INIT_BOARD_LIST";
export const GET_BOARD_LIST_ASYNC = "GET_BOARD_LIST_ASYNC";
export const GET_BOARD_LIST = "GET_BOARD_LIST";
export const CHANGE_BOARD_LIST_LOADING = "CHANGE_BOARD_LIST_LOADING";
export const GET_BOARD_LIST_TYPE_ALL_ASYNC = "GET_BOARD_LIST_TYPE_ALL_ASYNC";
export const GET_BOARD_LIST_TYPE_QUESTION_ASYNC = "GET_BOARD_LIST_TYPE_QUESTION_ASYNC";
export const GET_BAORD_LIST_TYPE_SHARE_ASYNC = "GET_BAORD_LIST_TYPE_SHARE_ASYNC";
export const GET_BAORD_LIST_TYPE_FREE_ASYNC = "GET_BAORD_LIST_TYPE_FREE_ASYNC";

// [게시판 상세] -----------------------------------------
export const GET_BOARD_DETAIL_ASYNC = "GET_BOARD_DETAIL_ASYNC";
export const GET_BOARD_DETAIL_COMMENT_LIST_ASYNC = "GET_BOARD_DETAIL_COMMENT_LIST_ASYNC";
export const GET_BOARD_DETAIL_COMMENT_LIST = "GET_BOARD_DETAIL_COMMENT_LIST";
export const CHANGE_BOARD_DETAIL_COMMENT_EDITOR_SHEET = "CHANGE_BOARD_DETAIL_COMMENT_EDITOR_SHEET";
export const GET_BAORD_DETAIL_COMMENT_DETAIL_ASYNC = "GET_BAORD_DETAIL_COMMENT_DETAIL_ASYNC";
export const INIT_BAORD_DETAIL_COMMENT_DETAIL_ASYNC = "INIT_BAORD_DETAIL_COMMENT_DETAIL_ASYNC";
export const REPLACE_BOARD_DETAIL_COMMENT_LIST_ITEM = "REPLACE_BOARD_DETAIL_COMMENT_LIST_ITEM";

// [게시판 댓글 CRUD] -----------------------------------------
export const POST_BOARD_COMMENT_ASYNC = "POST_BOARD_COMMENT_ASYNC";
export const PUT_BOARD_COMMENT_ASYNC = "PUT_BOARD_COMMENT_ASYNC";
export const REMOVE_BAORD_COMMENT_ASYNC = "REMOVE_BAORD_COMMENT_ASYNC";

// [다이얼로그 공통] -----------------------------------------
// [알림] 다이얼로그 상태 변경
export const CHANGE_DIALOG_ALERT = "CHANGE_DIALOG_ALERT";
// [알림] 다이얼로그 상태 초기화
export const INIT_DIALOG_ALERT = "INIT_DIALOG_ALERT";
// [확인] 다이얼로그 상태 변경
export const CHANGE_DIALOG_CONFIRM = "CHANGE_DIALOG_CONFIRM";
// [확인] 다이얼로그 상태 초기화
export const INIT_DIALOG_CONFIRM = "INIT_DIALOG_CONFIRM";

// [회원] -----------------------------------------
// [회원가입] 인증메일 발송 및 인증키 획득
export const SIGNUP_SEND_MAIL_AUTHCODE_ASYNC = "SIGNUP_SEND_MAIL_AUTHCODE_ASYNC";
// [회원가입] 회원가입
export const SIGNUP_ASYNC = "SIGNUP_ASYNC";
// [로그인] 로그인
export const SIGNIN_ASYNC = "SIGNIN_ASYNC";
// [회원] 회원정보 조회
export const GET_USER_ASYNC = "GET_USER_ASYNC";
// [회원] 회원정보 초기화
export const INIT_USER_ASYNC = "INIT_USER_ASYNC";

// [회원 CRUD] -----------------------------------------
export const PUT_USER_AVATAR_ASYNC = "PUT_USER_AVATAR_ASYNC";
export const PUT_USER_NAME_ASYNC = "PUT_USER_NAME_ASYNC";
export const PUT_USER_PASSWORD_ASYNC = "PUT_USER_PASSWORD_ASYNC";

// [회원 정보조회 리스트] -----------------------------------------
export const GET_USER_BOARD_LIST_ASYNC = "GET_USER_BOARD_LIST_ASYNC";
export const INIT_USER_BOARD_LIST = "INIT_USER_BOARD_LIST";
export const GET_USER_COMMENT_LIST_ASYNC = "GET_USER_COMMENT_LIST_ASYNC";
export const INIT_USER_COMMENT_LIST = "INIT_USER_COMMENT_LIST";
export const REPLACE_USER_BOARD_COMMENT_LIST_ITEM = "REPLACE_USER_BOARD_COMMENT_LIST_ITEM";

// [포트폴리오 리스트] -----------------------------------------
export const GET_PORTFOLIO_DETAIL_ASYNC = "GET_PORTFOLIO_DETAIL_ASYNC";
export const GET_PORTFOLIO_LIST_ASYNC = "GET_PORTFOLIO_LIST_ASYNC";
export const GET_PORTFOLIO_LIST = "GET_PORTFOLIO_LIST";
export const ADD_PORTFOLIO_LIST_ITEM = "ADD_PORTFOLIO_LIST_ITEM";
export const REPLACE_PORTFOLIO_LIST_ITEM = "REPLACE_PORTFOLIO_LIST_ITEM";

// [포트폴리오 CRUD] -----------------------------------------
export const POST_PORTFOLIO_ASYNC = "POST_PORTFOLIO_ASYNC";
export const PUT_PORTFOLIO_ASYNC = "PUT_PORTFOLIO_ASYNC";
export const PUT_PORTFOLIO_USER_ASYNC = "PUT_PORTFOLIO_USER_ASYNC";
export const REMOVE_PORTFOLIO_ASYNC = "REMOVE_PORTFOLIO_ASYNC";

export default {
    // [게시판 공통] -----------------------------------------
    CHANGE_BOARD_TYPE_TAB: CHANGE_BOARD_TYPE_TAB,
    CHANGE_BOARD_TYPE_FILTER: CHANGE_BOARD_TYPE_FILTER,
    CHANGE_BOARD_TYPE_EDITOR: CHANGE_BOARD_TYPE_EDITOR,
    GET_BOARD_TYPE_ASYNC: GET_BOARD_TYPE_ASYNC,
    CHANGE_BOARD_CATEGORY_FILTER: CHANGE_BOARD_CATEGORY_FILTER,
    CHANGE_BOARD_CATEGORY_EDITOR: CHANGE_BOARD_CATEGORY_EDITOR,
    GET_BOARD_CATEGORY_ASYNC: GET_BOARD_CATEGORY_ASYNC,
    // [게시판 CRUD] -----------------------------------------
    POST_BOARD_ASYNC: POST_BOARD_ASYNC,
    PUT_BOARD_ASYNC: PUT_BOARD_ASYNC,
    REMOVE_BOARD_ASYNC: REMOVE_BOARD_ASYNC,
    // [게시판 검색(자동완성) 리스트] -----------------------------------------
    GET_SEARCH_BOARD_AUTO_COMLETE_LIST: GET_SEARCH_BOARD_AUTO_COMLETE_LIST,
    INIT_SEARCH_BOARD_AUTO_COMLETE_LIST: INIT_SEARCH_BOARD_AUTO_COMLETE_LIST,
    // [게시판 리스트] -----------------------------------------
    INIT_BOARD_LIST: INIT_BOARD_LIST,
    GET_BOARD_LIST_ASYNC: GET_BOARD_LIST_ASYNC,
    GET_BOARD_LIST: GET_BOARD_LIST,
    CHANGE_BOARD_LIST_LOADING: CHANGE_BOARD_LIST_LOADING,
    GET_BOARD_LIST_TYPE_ALL_ASYNC: GET_BOARD_LIST_TYPE_ALL_ASYNC,
    GET_BOARD_LIST_TYPE_QUESTION_ASYNC: GET_BOARD_LIST_TYPE_QUESTION_ASYNC,
    GET_BAORD_LIST_TYPE_SHARE_ASYNC: GET_BAORD_LIST_TYPE_SHARE_ASYNC,
    GET_BAORD_LIST_TYPE_FREE_ASYNC: GET_BAORD_LIST_TYPE_FREE_ASYNC,
    // [게시판 상세] -----------------------------------------
    GET_BOARD_DETAIL_ASYNC: GET_BOARD_DETAIL_ASYNC,
    GET_BOARD_DETAIL_COMMENT_LIST_ASYNC: GET_BOARD_DETAIL_COMMENT_LIST_ASYNC,
    GET_BOARD_DETAIL_COMMENT_LIST: GET_BOARD_DETAIL_COMMENT_LIST,
    CHANGE_BOARD_DETAIL_COMMENT_EDITOR_SHEET: CHANGE_BOARD_DETAIL_COMMENT_EDITOR_SHEET,
    GET_BAORD_DETAIL_COMMENT_DETAIL_ASYNC: GET_BAORD_DETAIL_COMMENT_DETAIL_ASYNC,
    INIT_BAORD_DETAIL_COMMENT_DETAIL_ASYNC: INIT_BAORD_DETAIL_COMMENT_DETAIL_ASYNC,
    REPLACE_BOARD_DETAIL_COMMENT_LIST_ITEM: REPLACE_BOARD_DETAIL_COMMENT_LIST_ITEM,
    // [게시판 댓글 CRUD] -----------------------------------------
    POST_BOARD_COMMENT_ASYNC: POST_BOARD_COMMENT_ASYNC,
    PUT_BOARD_COMMENT_ASYNC: PUT_BOARD_COMMENT_ASYNC,
    REMOVE_BAORD_COMMENT_ASYNC: REMOVE_BAORD_COMMENT_ASYNC,
    // [다이얼로그 공통] -----------------------------------------
    CHANGE_DIALOG_ALERT: CHANGE_DIALOG_ALERT,
    INIT_DIALOG_ALERT: INIT_DIALOG_ALERT,
    CHANGE_DIALOG_CONFIRM: CHANGE_DIALOG_CONFIRM,
    INIT_DIALOG_CONFIRM: INIT_DIALOG_CONFIRM,
    // [회원] -----------------------------------------
    SIGNUP_SEND_MAIL_AUTHCODE_ASYNC: SIGNUP_SEND_MAIL_AUTHCODE_ASYNC,
    SIGNUP_ASYNC: SIGNUP_ASYNC,
    SIGNIN_ASYNC: SIGNIN_ASYNC,
    GET_USER_ASYNC: GET_USER_ASYNC,
    INIT_USER_ASYNC: INIT_USER_ASYNC,
    // [회원 CRUD] -----------------------------------------
    PUT_USER_AVATAR_ASYNC: PUT_USER_AVATAR_ASYNC,
    PUT_USER_NAME_ASYNC: PUT_USER_NAME_ASYNC,
    PUT_USER_PASSWORD_ASYNC: PUT_USER_PASSWORD_ASYNC,
    // [회원 정보조회 리스트] -----------------------------------------
    GET_USER_BOARD_LIST_ASYNC: GET_USER_BOARD_LIST_ASYNC,
    INIT_USER_BOARD_LIST: INIT_USER_BOARD_LIST,
    GET_USER_COMMENT_LIST_ASYNC: GET_USER_COMMENT_LIST_ASYNC,
    INIT_USER_COMMENT_LIST: INIT_USER_COMMENT_LIST,
    REPLACE_USER_BOARD_COMMENT_LIST_ITEM: REPLACE_USER_BOARD_COMMENT_LIST_ITEM,
    // [포트폴리오 리스트] -----------------------------------------
    GET_PORTFOLIO_DETAIL_ASYNC: GET_PORTFOLIO_DETAIL_ASYNC,
    GET_PORTFOLIO_LIST_ASYNC: GET_PORTFOLIO_LIST_ASYNC,
    GET_PORTFOLIO_LIST: GET_PORTFOLIO_LIST,
    ADD_PORTFOLIO_LIST_ITEM: ADD_PORTFOLIO_LIST_ITEM,
    REPLACE_PORTFOLIO_LIST_ITEM: REPLACE_PORTFOLIO_LIST_ITEM,
    // [포트폴리오 CRUD] -----------------------------------------
    POST_PORTFOLIO_ASYNC: POST_PORTFOLIO_ASYNC,
    PUT_PORTFOLIO_ASYNC: PUT_PORTFOLIO_ASYNC,
    PUT_PORTFOLIO_USER_ASYNC: PUT_PORTFOLIO_USER_ASYNC,
    REMOVE_PORTFOLIO_ASYNC: REMOVE_PORTFOLIO_ASYNC
}